# .goreleaser.yml
# Build customization
builds:
  - binary: suitesync
    goos:
      # - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  files:
    - README.md
    - ci/circleci-example.yml