# .goreleaser.yml
before:
  hooks:
    - make pack-restlet
# Build customization
builds:
  - binary: suitesync
    goos:
      # - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  files:
    - init.sh
    - urls
    - restlet.tar.gz
    - README.md